general {
    lock_cmd = qs -c noctalia-shell ipc --any-display call lockScreen lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = qs -c noctalia-shell ipc --any-display call monitors on
    ignore_dbus_inhibit = false
}

# Lock screen after 30 minutes of inactivity
listener {
    timeout = 1800
    on-timeout = qs -c noctalia-shell ipc --any-display call lockScreen lock
}

# Turn off screens 30 seconds after locking
listener {
    timeout = 1830
    on-timeout = qs -c noctalia-shell ipc --any-display call monitors off
    on-resume = qs -c noctalia-shell ipc --any-display call monitors on
}
